// export * from './game.module';
export * from './game-area.object';
export * from './game.objects.component';
export * from './game.models';
export * from './game-area.view.component';
export * from './animator.component';
export * from './ObjectLogic/movement.component';
export * from './ObjectLogic/postion.component';
export * from './ObjectLogic/updateFrame.component';
export * from './ObjectLogic/crashLogic.component';
export * from './ObjectLogic/ammo.component';
export * from './Design/objectDesign.component';
export * from './GameAreaLogic/object-category-setter';
export * from './ObjectLogic/groupItem';
export * from './ObjectLogic/comparer';
